Rangos_ES = {
    "Iron 1": "Hierro 1",
    "Iron 2": "Hierro 2",
    "Iron 3": "Hierro 3",
    "Bronze 1": "Bronce 1",
    "Bronze 2": "Bronce 2",
    "Bronze 3": "Bronce 3",
    "Silver 1": "Plata 1",
    "Silver 2": "Plata 2",
    "Silver 3": "Plata 3",
    "Gold 1": "Oro 1",
    "Gold 2": "Oro 2",
    "Gold 3": "Oro 3",
    "Platinum 1": "Platino 1",
    "Platinum 2": "Platino 2",
    "Platinum 3": "Platino 3",
    "Diamond 1": "Diamante 1",
    "Diamond 2": "Diamante 2",
    "Diamond 3": "Diamante 3",
    "Ascendant 1": "Ascendente 1",
    "Ascendant 2": "Ascendente 2",
    "Ascendant 3": "Ascendente 3",
    "Immortal 1": "Inmortal 1",
    "Immortal 2": "Inmortal 2",
    "Immortal 3": "Inmortal 3",
    "Radiant": "Radiante",
}

#Si alguien ve esto es nomas para que aparezcan en español JAJAJAJ, Es que me da cosita.
